### PR TITLE
SDL2 support

### PR DESCRIPTION
**Pull request by sergiobenrocha2**
I did some tests, I think it's in a good shape.

SDL 1.2 support was dropped.

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
Take a look at the google groups too.

**Comment by fredbcode** [comment]
Great thanks

**Comment by fredbcode** [comment]
Hi Sergio,

Maybe I made something wrong, but there is something wrong now with usb pad (no matter the model) 
Steps to reproduce easily:

1 - Remove config.xml
2 - start cabrio -> Wizard doesn't see the pad
3  - Return to the "old" binary all is ok

Any idea ?

**Comment by sergiobenrocha2** [comment]
It's an SDL2 issue, take a look at https://groups.google.com/forum/#!topic/cabrio-fe-dev/O2jHwIUVV5o

If you Alt+Tab, it'll work.

**Comment by fredbcode** [comment]
Yes I saw sorry for the noise
Very bad news ...

**Comment by sergiobenrocha2** [comment]
I wonder if there is some workaround for this issue.

**Comment by fredbcode** [comment]
Really annoying, cabrio-fe is unusable in mamecab 
It surprises me that there is not more complaint SDL 2.0.2 is very popular

**Comment by sergiobenrocha2** [comment]
Found an workaround, calls cabrio on terminal with:

SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS=1 cabrio

**Comment by fredbcode** [comment]
Sergio,
Maybe we can change the code to add SDL_setenv("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1", 0); before SDL_INIT_JOYSTICK

**Pull request merged**
